// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOlVFYEnGOLat61d8tK-6BoVUddlkb6uA',
    appId: '1:374660438138:web:99d1d2933ff3682b0303c3',
    messagingSenderId: '374660438138',
    projectId: 'capital-commons',
    authDomain: 'capital-commons.firebaseapp.com',
    storageBucket: 'capital-commons.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbUS3tMatnKP9eXjWKMEyEJBjcd6jlPEI',
    appId: '1:374660438138:android:68537e50b6642c8f0303c3',
    messagingSenderId: '374660438138',
    projectId: 'capital-commons',
    storageBucket: 'capital-commons.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsPFJO3NQgBbbp-CVk_u9RZDlc5fW_Ywc',
    appId: '1:374660438138:ios:8c17b16589d845260303c3',
    messagingSenderId: '374660438138',
    projectId: 'capital-commons',
    storageBucket: 'capital-commons.firebasestorage.app',
    iosBundleId: 'com.example.capitalCommons',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsPFJO3NQgBbbp-CVk_u9RZDlc5fW_Ywc',
    appId: '1:374660438138:ios:8c17b16589d845260303c3',
    messagingSenderId: '374660438138',
    projectId: 'capital-commons',
    storageBucket: 'capital-commons.firebasestorage.app',
    iosBundleId: 'com.example.capitalCommons',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOlVFYEnGOLat61d8tK-6BoVUddlkb6uA',
    appId: '1:374660438138:web:3267cf04c98b27850303c3',
    messagingSenderId: '374660438138',
    projectId: 'capital-commons',
    authDomain: 'capital-commons.firebaseapp.com',
    storageBucket: 'capital-commons.firebasestorage.app',
  );
}
